# Generated by Django 4.2.5 on 2023-10-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listing_photo_1_alter_listing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%Y/%m/%d/'),
        ),
    ]
