# Generated by Django 5.0.1 on 2024-09-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_listing_latitute_listing_longitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='houseSquareYard',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='latitute',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitute',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='video',
        ),
    ]
