# Generated by Django 4.2 on 2023-09-30 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking',
            new_name='listing',
        ),
    ]
