# Generated by Django 4.2.5 on 2023-10-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
