# Generated by Django 4.2.5 on 2023-10-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_contactus_email_contactus_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_no',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
