# Generated by Django 4.2.5 on 2023-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_payment_card_no_payment_month_payment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='name_on_card',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
