# Generated by Django 4.2.5 on 2023-10-21 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment_name_on_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_done',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.payment'),
        ),
    ]
