# Generated by Django 4.2.5 on 2023-10-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_booking_payment_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'House Tour', 'verbose_name_plural': 'House tour'},
        ),
    ]
