# Generated by Django 4.2.5 on 2023-11-03 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_alter_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='agreement',
        ),
    ]
