# Generated by Django 4.2.5 on 2023-11-03 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_booking_agreement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='id_card',
            new_name='email',
        ),
    ]
