# Generated by Django 4.2.5 on 2023-11-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_rename_id_card_booking_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='card_no',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
