# Generated by Django 4.2.5 on 2023-11-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='helptransportation',
            name='house_tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.booking'),
        ),
    ]
