# Generated by Django 4.2.5 on 2023-11-05 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0014_helptransportation_house_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_done',
        ),
    ]
