# Generated by Django 5.0.1 on 2024-09-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_booking_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HelpTransportation',
        ),
    ]
